version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: devevolution-db
    restart: always
    environment:
      POSTGRES_USER: DevEvo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devevolution_db
    ports:
      - "5432:5432"
    volumes:
      - devevolution_data:/var/lib/postgresql/data

volumes:
  devevolution_data: