# ==========================================
# PERFIL: POSTGRESQL (Sua Máquina)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/devevolution_db
spring.datasource.username=DevEvo
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect