# Configurações de conexão com o PostgreSQL rodando no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/devevolution_db
spring.datasource.username=DevEvo
spring.datasource.password=123

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect