# ==========================================
# CONFIGURAÇÕES COMUNS (SERVE PARA AMBOS)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Segurança JWT
security.jwt.secret=dev-evolution-secret-key-change-me-1234567890
security.jwt.expiration-minutes=60

# Define qual banco vai rodar por padrão (o seu Postgres)
spring.profiles.active=postgres